# YAO_CONFIG__BUILD_TYPE
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(YAO_CONFIG__BUILD_TYPE YAO_CONFIG__BUILD_TYPE__DEBUG)
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
  set(YAO_CONFIG__BUILD_TYPE YAO_CONFIG__BUILD_TYPE__RELEASE)
endif()

# YAO_CONFIG__COMPILER
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set(YAO_CONFIG__COMPILER YAO_CONFIG__COMPILER__GNU)
elseif((CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
       (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang"))
  set(YAO_CONFIG__COMPILER YAO_CONFIG__COMPILER__CLANG)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  set(YAO_CONFIG__COMPILER YAO_CONFIG__COMPILER__MSVC)
endif()

# YAO_CONFIG__PRINT_FORMAT
if(NOT DEFINED YAO_CONFIG__PRINT_FORMAT)
  set(YAO_CONFIG__PRINT_FORMAT YAO_CONFIG__PRINT_FORMAT__FUNCTION)
endif()

message(
  "YAO_CONFIG:\n"
  "  YAO_CONFIG__BUILD_TYPE = ${YAO_CONFIG__BUILD_TYPE}\n"
  "  YAO_CONFIG__COMPILER = ${YAO_CONFIG__COMPILER}\n"
  "  YAO_CONFIG__PRINT_FORMAT = ${YAO_CONFIG__PRINT_FORMAT}"
)

configure_file(config.hpp.in ${PROJECT_SOURCE_DIR}/inc/yao/config.hpp)
