function(yao__host_sys_info__common KEY)
  cmake_host_system_information(RESULT YAO_INFO__${KEY} QUERY ${KEY})
  message("  YAO_INFO__${KEY} = ${YAO_INFO__${KEY}}")
endfunction()

function(yao__host_sys_info__memory KEY)
  cmake_host_system_information(RESULT YAO_INFO__${KEY} QUERY ${KEY})
  message("  YAO_INFO__${KEY} = ${YAO_INFO__${KEY}} MiB")
endfunction()

message("YAO_INFO__PROCESSOR:")
yao__host_sys_info__common(PROCESSOR_NAME)
yao__host_sys_info__common(PROCESSOR_DESCRIPTION)
yao__host_sys_info__common(NUMBER_OF_PHYSICAL_CORES)
yao__host_sys_info__common(NUMBER_OF_LOGICAL_CORES)

message("YAO_INFO__MEMORY:")
yao__host_sys_info__memory(TOTAL_PHYSICAL_MEMORY)
yao__host_sys_info__memory(AVAILABLE_PHYSICAL_MEMORY)
yao__host_sys_info__memory(TOTAL_VIRTUAL_MEMORY)
yao__host_sys_info__memory(AVAILABLE_VIRTUAL_MEMORY)

message("YAO_INFO__OS:")
yao__host_sys_info__common(OS_NAME)
yao__host_sys_info__common(OS_RELEASE)
yao__host_sys_info__common(OS_VERSION)
yao__host_sys_info__common(OS_PLATFORM)

cmake_host_system_information(RESULT YAO_INFO__DISTRIB_ QUERY DISTRIB_INFO)
if(NOT YAO_INFO__DISTRIB_ STREQUAL "")
  message("YAO_INFO__DISTRIB:")
  foreach(ITEM IN LISTS YAO_INFO__DISTRIB_)
    message("  ${ITEM} = ${${ITEM}}")
  endforeach()
endif()
