on:
  push:
    branches: [main]

jobs:
  debug:
    strategy:
      fail-fast: false

      matrix:
        GITHUB_RUNNER: [ubuntu-latest, macos-latest, windows-latest]
        CMAKE_CXX_COMPILER: [c++, clang++]
        exclude:
          - GITHUB_RUNNER: macos-latest
            CMAKE_CXX_COMPILER: clang++
          - GITHUB_RUNNER: windows-latest
            CMAKE_CXX_COMPILER: clang++

    runs-on: ${{ matrix.GITHUB_RUNNER }}

    steps:
      - uses: actions/checkout@v4

      - run: >
          bash cmd/debug.sh
          -D CMAKE_CXX_COMPILER=${{ matrix.CMAKE_CXX_COMPILER }}

  release:
    needs: debug

    strategy:
      fail-fast: false

      matrix:
        GITHUB_RUNNER: [ubuntu-latest, macos-latest, windows-latest]
        CMAKE_CXX_COMPILER: [c++, clang++]
        exclude:
          - GITHUB_RUNNER: macos-latest
            CMAKE_CXX_COMPILER: clang++
          - GITHUB_RUNNER: windows-latest
            CMAKE_CXX_COMPILER: clang++

    runs-on: ${{ matrix.GITHUB_RUNNER }}

    steps:
      - uses: actions/checkout@v4

      - run: >
          bash cmd/release.sh
          -D CMAKE_CXX_COMPILER=${{ matrix.CMAKE_CXX_COMPILER }}
