on:
  push:
    branches: [main]

jobs:
  debug:
    strategy:
      fail-fast: false

      matrix:
        GITHUB_RUNNER: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.GITHUB_RUNNER }}

    steps:
      - uses: actions/checkout@v4

      - run: bash cmd/debug.sh

  release:
    needs: debug

    strategy:
      fail-fast: false

      matrix:
        GITHUB_RUNNER: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.GITHUB_RUNNER }}

    steps:
      - uses: actions/checkout@v4

      - run: bash cmd/release.sh
