name: Release various config

on:
  workflow_run:
    workflows: [Release default config]
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: false

      matrix:
        GITHUB_RUNNER: [ubuntu-latest, macos-latest, windows-latest]
        CMAKE_CXX_COMPILER: [c++, clang++]
        exclude:
          - GITHUB_RUNNER: macos-latest
            CMAKE_CXX_COMPILER: clang++
          - GITHUB_RUNNER: windows-latest
            CMAKE_CXX_COMPILER: clang++

        CMAKE_BUILD_TYPE: [Release]
        YAO_CONFIG__OSPRINTF:
          [YAO_CONFIG__OSPRINTF__FUNCTION, YAO_CONFIG__OSPRINTF__TEMPLATE]
        YAO_CONFIG__LAB__RE_ERASED_STATE:
          [
            YAO_CONFIG__LAB__RE_ERASED_STATE__VIRTUAL_FUNCTION,
            YAO_CONFIG__LAB__RE_ERASED_STATE__FUNCTION_POINTER,
            YAO_CONFIG__LAB__RE_ERASED_STATE__FUNCTION_OBJECT,
          ]

    runs-on: ${{ matrix.GITHUB_RUNNER }}

    steps:
      - uses: actions/checkout@v4

      - name: Config
        run: >
          cmake -B build
          -D CMAKE_CXX_COMPILER=${{ matrix.CMAKE_CXX_COMPILER }}
          -D CMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }}
          -D YAO_CONFIG__OSPRINTF=${{ matrix.YAO_CONFIG__OSPRINTF }}
          -D YAO_CONFIG__LAB__RE_ERASED_STATE=${{ matrix.YAO_CONFIG__LAB__RE_ERASED_STATE }}

      - name: Build
        run: >
          cmake --build build
          --config ${{ matrix.CMAKE_BUILD_TYPE }}
          --parallel

      - name: Test
        run: >
          ctest --test-dir build
          --build-config ${{ matrix.CMAKE_BUILD_TYPE }}
          --parallel
